/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolab_katherine_fabio;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author KATHERINE
 */
public class principal_proyectolab extends javax.swing.JFrame {

    /**
     * Creates new form principal_proyectolab
     */
    public principal_proyectolab() {
        initComponents();
        
        m_usuario_candidato.setEnabled(false);
        m_usuario_comun.setEnabled(false);
        mi_logout.setEnabled(false);
        mi_login.setEnabled(false);
        bt_guardar_cambios_perfil.setEnabled(false);
        bt_modificar.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo2 = new javax.swing.ButtonGroup();
        Sexo = new javax.swing.ButtonGroup();
        jd_UsuarioCandidato = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_usuario_c2 = new javax.swing.JTextField();
        ag_usuario_candidato = new javax.swing.JButton();
        rb_femenino_c2 = new javax.swing.JRadioButton();
        rb_masculino_c2 = new javax.swing.JRadioButton();
        tf_nombre_c2 = new javax.swing.JTextField();
        tf_correo_c2 = new javax.swing.JTextField();
        tf_contraseña_c2 = new javax.swing.JPasswordField();
        js_fecha_c2 = new javax.swing.JSpinner();
        jLabel44 = new javax.swing.JLabel();
        jd_UsuarioComun = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_usuario_c1 = new javax.swing.JTextField();
        tf_nombre_c1 = new javax.swing.JTextField();
        tf_correo_c1 = new javax.swing.JTextField();
        tf_direccion_c1 = new javax.swing.JTextField();
        rb_femenino_c1 = new javax.swing.JRadioButton();
        rb_masculino_c1 = new javax.swing.JRadioButton();
        ag_usuario_comun = new javax.swing.JButton();
        tf_contraseña_c1 = new javax.swing.JPasswordField();
        js_fecha_c1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_archivo_c1 = new javax.swing.JTextArea();
        jLabel43 = new javax.swing.JLabel();
        menu_Usuario_Comun = new javax.swing.JDialog();
        tab = new javax.swing.JTabbedPane();
        perfil = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_usuario1 = new javax.swing.JTextField();
        tf_nombre1 = new javax.swing.JTextField();
        tf_sexo1 = new javax.swing.JTextField();
        tf_correo1 = new javax.swing.JTextField();
        tf_direccion1 = new javax.swing.JTextField();
        tf_contraseña1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_archivo_1 = new javax.swing.JTextArea();
        bt_modificar = new javax.swing.JButton();
        bt_verdatos_perfil = new javax.swing.JButton();
        js_fecha1 = new javax.swing.JSpinner();
        bt_guardar_cambios_perfil = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        usuarios = new javax.swing.JPanel();
        cb_amigos = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_amigos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        candidatos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_candidatos2 = new javax.swing.JList<>();
        dejar_seguir = new javax.swing.JButton();
        cb_candidatos = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        publicaciones = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_publicaciones = new javax.swing.JTextArea();
        cb_candidatos_publicaciones = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        messenger = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_mensajes = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        ta_mensajes1 = new javax.swing.JTextArea();
        jLabel52 = new javax.swing.JLabel();
        actas = new javax.swing.JPanel();
        cargra_acta = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        ta_acta = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        tf_votos = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        login = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        iniciar_sesion = new javax.swing.JButton();
        tf_contraseña = new javax.swing.JPasswordField();
        tf_usuario = new javax.swing.JTextField();
        imah = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        menu_usuarioCandidato = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        area_publicacion = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        tf_nombre_c3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tf_usuario_c3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        rb_femenino_c3 = new javax.swing.JRadioButton();
        rb_masculino_c3 = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        tf_contraseña_c3 = new javax.swing.JPasswordField();
        jLabel32 = new javax.swing.JLabel();
        tf_correo_c3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        js_fecha_c3 = new javax.swing.JSpinner();
        jButton7 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        mensaje = new javax.swing.JDialog();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        cb_amigos_mensaje = new javax.swing.JComboBox<>();
        tf_asunto = new javax.swing.JTextField();
        ta_mensaje = new javax.swing.JTextField();
        enviar_mensaje = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        imagen_principal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mi_login = new javax.swing.JMenuItem();
        mi_logout = new javax.swing.JMenuItem();
        m_usuario_comun = new javax.swing.JMenu();
        m_usuario_candidato = new javax.swing.JMenu();

        jd_UsuarioCandidato.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("Usuario Candidato");
        jd_UsuarioCandidato.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 34, -1, 56));

        jLabel11.setText("Usuario");
        jd_UsuarioCandidato.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 111, -1, -1));

        jLabel12.setText("Contraseña");
        jd_UsuarioCandidato.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 111, -1, -1));

        jLabel13.setText("Nombre Completo");
        jd_UsuarioCandidato.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 202, -1, -1));

        jLabel14.setText("Correo");
        jd_UsuarioCandidato.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 193, -1, -1));

        jLabel15.setText("Sexo");
        jd_UsuarioCandidato.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 275, -1, -1));

        jLabel16.setText("Fecha de nacimiento");
        jd_UsuarioCandidato.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 275, -1, -1));

        tf_usuario_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuario_c2ActionPerformed(evt);
            }
        });
        jd_UsuarioCandidato.getContentPane().add(tf_usuario_c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 108, 162, -1));

        ag_usuario_candidato.setText("Agregar");
        ag_usuario_candidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ag_usuario_candidatoMouseClicked(evt);
            }
        });
        jd_UsuarioCandidato.getContentPane().add(ag_usuario_candidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 375, 148, 58));

        sexo2.add(rb_femenino_c2);
        rb_femenino_c2.setText("F");
        jd_UsuarioCandidato.getContentPane().add(rb_femenino_c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 271, -1, -1));

        sexo2.add(rb_masculino_c2);
        rb_masculino_c2.setSelected(true);
        rb_masculino_c2.setText("M");
        jd_UsuarioCandidato.getContentPane().add(rb_masculino_c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 271, -1, -1));
        jd_UsuarioCandidato.getContentPane().add(tf_nombre_c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 199, 162, -1));
        jd_UsuarioCandidato.getContentPane().add(tf_correo_c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 190, 166, -1));
        jd_UsuarioCandidato.getContentPane().add(tf_contraseña_c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 108, 166, -1));

        js_fecha_c2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(915227160000L), null, new java.util.Date(946763160000L), java.util.Calendar.DAY_OF_YEAR));
        jd_UsuarioCandidato.getContentPane().add(js_fecha_c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(563, 272, -1, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/fondo1 (1).jpg"))); // NOI18N
        jLabel44.setText("jLabel44");
        jd_UsuarioCandidato.getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 590));

        jd_UsuarioComun.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Usuario Común ");
        jd_UsuarioComun.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel2.setText("Usuario");
        jd_UsuarioComun.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 102, -1, -1));

        jLabel3.setText("Contraseña");
        jd_UsuarioComun.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 102, -1, -1));

        jLabel4.setText("fecha de nacimiento");
        jd_UsuarioComun.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 251, -1, -1));

        jLabel5.setText("Correo");
        jd_UsuarioComun.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 177, -1, -1));

        jLabel6.setText("sexo");
        jd_UsuarioComun.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 251, -1, -1));

        jLabel7.setText("Nombre Completo");
        jd_UsuarioComun.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 177, -1, -1));

        jLabel8.setText("Dirección");
        jd_UsuarioComun.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 341, -1, -1));

        jLabel9.setText("Archivo de texto");
        jd_UsuarioComun.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 341, -1, -1));
        jd_UsuarioComun.getContentPane().add(tf_usuario_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 99, 174, -1));
        jd_UsuarioComun.getContentPane().add(tf_nombre_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 174, 174, -1));
        jd_UsuarioComun.getContentPane().add(tf_correo_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 214, -1));
        jd_UsuarioComun.getContentPane().add(tf_direccion_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 338, 174, -1));

        Sexo.add(rb_femenino_c1);
        rb_femenino_c1.setText("F");
        jd_UsuarioComun.getContentPane().add(rb_femenino_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 247, -1, -1));

        Sexo.add(rb_masculino_c1);
        rb_masculino_c1.setSelected(true);
        rb_masculino_c1.setText("M");
        jd_UsuarioComun.getContentPane().add(rb_masculino_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 247, -1, -1));

        ag_usuario_comun.setText("Agregar");
        ag_usuario_comun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ag_usuario_comunMouseClicked(evt);
            }
        });
        jd_UsuarioComun.getContentPane().add(ag_usuario_comun, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 443, 145, 51));
        jd_UsuarioComun.getContentPane().add(tf_contraseña_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 214, -1));

        js_fecha_c1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(915227160000L), null, new java.util.Date(946763160000L), java.util.Calendar.DAY_OF_YEAR));
        jd_UsuarioComun.getContentPane().add(js_fecha_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 220, -1));

        ta_archivo_c1.setColumns(20);
        ta_archivo_c1.setRows(5);
        jScrollPane1.setViewportView(ta_archivo_c1);

        jd_UsuarioComun.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 220, 100));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/fondo1 (1).jpg"))); // NOI18N
        jd_UsuarioComun.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 540));

        tab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabStateChanged(evt);
            }
        });

        perfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("Nombre");
        perfil.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 140, 67, -1));

        jLabel20.setText("Usuario");
        perfil.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 204, -1, -1));

        jLabel21.setText("Contraseña ");
        perfil.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 274, -1, -1));

        jLabel22.setText("Correo");
        perfil.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 441, -1, -1));

        jLabel23.setText("Sexo");
        perfil.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel24.setText("fecha de nacimiento");
        perfil.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 204, -1, -1));

        jLabel25.setText("direccion");
        perfil.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 274, -1, -1));

        jLabel26.setText("Archivo de Texto");
        perfil.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 355, -1, -1));
        perfil.add(tf_usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 201, 163, -1));
        perfil.add(tf_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 137, 163, -1));
        perfil.add(tf_sexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 137, 261, -1));
        perfil.add(tf_correo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 438, 163, -1));
        perfil.add(tf_direccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 271, 261, -1));
        perfil.add(tf_contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 271, 163, -1));

        ta_archivo_1.setColumns(20);
        ta_archivo_1.setRows(5);
        jScrollPane2.setViewportView(ta_archivo_1);

        perfil.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 337, 270, 70));

        bt_modificar.setText("Modificar");
        bt_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificarMouseClicked(evt);
            }
        });
        perfil.add(bt_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 530, 116, 54));

        bt_verdatos_perfil.setText("VER DATOS PERFIL");
        bt_verdatos_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_verdatos_perfilMouseClicked(evt);
            }
        });
        perfil.add(bt_verdatos_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 40, -1, -1));

        js_fecha1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(-55879890540000L), null, new java.util.Date(-55879890540000L), java.util.Calendar.DAY_OF_MONTH));
        perfil.add(js_fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 189, -1, -1));

        bt_guardar_cambios_perfil.setText("Guardar cambios");
        bt_guardar_cambios_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardar_cambios_perfilMouseClicked(evt);
            }
        });
        perfil.add(bt_guardar_cambios_perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 530, -1, 54));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/background.jpg"))); // NOI18N
        jLabel48.setText("jLabel48");
        perfil.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 730));

        tab.addTab("Perfil", perfil);

        usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb_amigos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cb_amigos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_amigosItemStateChanged(evt);
            }
        });
        usuarios.add(cb_amigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 75, 597, 62));

        jLabel28.setText("Usuarios, agregar a mis amigos:");
        usuarios.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 37, 240, -1));

        jl_amigos.setModel(new DefaultListModel()
        );
        jScrollPane4.setViewportView(jl_amigos);

        usuarios.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 228, 597, 163));

        jButton1.setText("Eliminar de mis amigos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        usuarios.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 426, -1, -1));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/background.jpg"))); // NOI18N
        jLabel49.setText("jLabel48");
        usuarios.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 730));

        tab.addTab("Ver usuarios", usuarios);

        candidatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_candidatos2.setModel(new DefaultListModel()
        );
        jScrollPane3.setViewportView(jl_candidatos2);

        candidatos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 220, 735, 163));

        dejar_seguir.setText("Dejar de seguir");
        dejar_seguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dejar_seguirMouseClicked(evt);
            }
        });
        candidatos.add(dejar_seguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 421, -1, -1));

        cb_candidatos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_candidatosItemStateChanged(evt);
            }
        });
        candidatos.add(cb_candidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 54, 318, 67));

        jLabel27.setText("Elegir candidato para seguir");
        candidatos.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 16, -1, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/background.jpg"))); // NOI18N
        jLabel50.setText("jLabel48");
        candidatos.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 730));

        tab.addTab("Ver Candidatos", candidatos);

        publicaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ta_publicaciones.setColumns(20);
        ta_publicaciones.setRows(5);
        jScrollPane6.setViewportView(ta_publicaciones);

        publicaciones.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 152, 763, 445));

        cb_candidatos_publicaciones.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_candidatos_publicacionesItemStateChanged(evt);
            }
        });
        publicaciones.add(cb_candidatos_publicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 45, 201, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/background.jpg"))); // NOI18N
        jLabel51.setText("jLabel48");
        publicaciones.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 730));

        tab.addTab("Publicaciones", publicaciones);

        messenger.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Actualizar Buzon de entrada");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        messenger.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 103, 278, -1));

        ta_mensajes.setColumns(20);
        ta_mensajes.setRows(5);
        jScrollPane5.setViewportView(ta_mensajes);

        messenger.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 148, 293, 483));

        jButton3.setText("Nuevo mensaje");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        messenger.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 16, 176, -1));

        jButton6.setText("Actualizar Buzon de salida");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        messenger.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 103, 232, -1));

        ta_mensajes1.setColumns(20);
        ta_mensajes1.setRows(5);
        jScrollPane8.setViewportView(ta_mensajes1);

        messenger.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 148, 294, 483));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/background.jpg"))); // NOI18N
        jLabel52.setText("jLabel48");
        messenger.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 730));

        tab.addTab("Messenger", messenger);

        actas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargra_acta.setText("Cargar Acta");
        cargra_acta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cargra_actaMouseClicked(evt);
            }
        });
        actas.add(cargra_acta, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 33, -1, -1));

        ta_acta.setColumns(20);
        ta_acta.setRows(5);
        jScrollPane9.setViewportView(ta_acta);

        actas.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 78, 760, 251));

        jLabel42.setText("Numero de votos de esta acta:");
        actas.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 366, -1, 29));
        actas.add(tf_votos, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 367, 96, -1));

        jButton4.setText("Asignar votos");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        actas.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 440, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/background.jpg"))); // NOI18N
        jLabel53.setText("jLabel48");
        actas.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 730));

        tab.addTab("Actas", actas);

        javax.swing.GroupLayout menu_Usuario_ComunLayout = new javax.swing.GroupLayout(menu_Usuario_Comun.getContentPane());
        menu_Usuario_Comun.getContentPane().setLayout(menu_Usuario_ComunLayout);
        menu_Usuario_ComunLayout.setHorizontalGroup(
            menu_Usuario_ComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_Usuario_ComunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );
        menu_Usuario_ComunLayout.setVerticalGroup(
            menu_Usuario_ComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_Usuario_ComunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );

        login.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Usuario");
        login.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Contraseña");
        login.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, -1, -1));

        iniciar_sesion.setText("Iniciar Sesión");
        iniciar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciar_sesionMouseClicked(evt);
            }
        });
        login.getContentPane().add(iniciar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 630, -1, -1));
        login.getContentPane().add(tf_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 156, -1));
        login.getContentPane().add(tf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 156, -1));

        imah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/HP-MSN-icon.png"))); // NOI18N
        login.getContentPane().add(imah, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 550, 480));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/login.jpg"))); // NOI18N
        jLabel45.setText("jLabel45");
        login.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 700));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel37.setText("Nueva Publicacion");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        area_publicacion.setColumns(20);
        area_publicacion.setRows(5);
        jScrollPane7.setViewportView(area_publicacion);

        jPanel7.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 490, -1));

        jButton5.setText("Publicar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/background2.jpg"))); // NOI18N
        jPanel7.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 480));

        jTabbedPane2.addTab("Realizar Publicacion", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setText("Nombre Completo");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        jPanel8.add(tf_nombre_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 162, -1));

        jLabel29.setText("Usuario");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        tf_usuario_c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuario_c3ActionPerformed(evt);
            }
        });
        jPanel8.add(tf_usuario_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 162, -1));

        jLabel30.setText("Sexo");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        rb_femenino_c3.setText("F");
        jPanel8.add(rb_femenino_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        rb_masculino_c3.setSelected(true);
        rb_masculino_c3.setText("M");
        jPanel8.add(rb_masculino_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel31.setText("Contraseña");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));
        jPanel8.add(tf_contraseña_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 166, -1));

        jLabel32.setText("Correo");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));
        jPanel8.add(tf_correo_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 166, -1));

        jLabel33.setText("Fecha de nacimiento");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        js_fecha_c3.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(915227160000L), null, new java.util.Date(946763160000L), java.util.Calendar.DAY_OF_YEAR));
        jPanel8.add(js_fecha_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jButton7.setText("MODIFICAR");
        jPanel8.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 100, 70));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/background2.jpg"))); // NOI18N
        jPanel8.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        jTabbedPane2.addTab("Ver mi perfil", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setText("Mis Votos");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 63, -1, -1));

        jProgressBar1.setMaximum(180000);
        jProgressBar1.setStringPainted(true);
        jPanel9.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 173, 563, 64));

        jLabel35.setText("0");
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 135, 28, -1));

        jLabel36.setText("180,000");
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 135, -1, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/background2.jpg"))); // NOI18N
        jPanel9.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        jTabbedPane2.addTab("Ver estadistica de votos", jPanel9);

        javax.swing.GroupLayout menu_usuarioCandidatoLayout = new javax.swing.GroupLayout(menu_usuarioCandidato.getContentPane());
        menu_usuarioCandidato.getContentPane().setLayout(menu_usuarioCandidatoLayout);
        menu_usuarioCandidatoLayout.setHorizontalGroup(
            menu_usuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        menu_usuarioCandidatoLayout.setVerticalGroup(
            menu_usuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_usuarioCandidatoLayout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        mensaje.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setText("Para");
        mensaje.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 57, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setText("Asunto");
        mensaje.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 122, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel41.setText("mensaje");
        mensaje.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 272, -1, -1));

        cb_amigos_mensaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        mensaje.getContentPane().add(cb_amigos_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 54, 367, -1));
        mensaje.getContentPane().add(tf_asunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 119, 367, -1));
        mensaje.getContentPane().add(ta_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 195, 367, 175));

        enviar_mensaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enviar_mensaje.setText("Enviar");
        enviar_mensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviar_mensajeMouseClicked(evt);
            }
        });
        mensaje.getContentPane().add(enviar_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/plantilla-de-sobres-que-vuelan_23-2147501884.jpg"))); // NOI18N
        jLabel46.setText("jLabel46");
        mensaje.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 610));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/descarga.jpg"))); // NOI18N
        getContentPane().add(imagen_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, -1));

        jMenu1.setText("Elecciones");

        jMenu4.setText("Registro");

        jMenuItem2.setText("Usuario Comun");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Usuario Candidato");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);

        mi_login.setText("Login");
        mi_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_loginActionPerformed(evt);
            }
        });
        jMenu1.add(mi_login);

        mi_logout.setText("logout");
        mi_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_logoutActionPerformed(evt);
            }
        });
        jMenu1.add(mi_logout);

        jMenuBar1.add(jMenu1);

        m_usuario_comun.setText("Usuario Común");
        m_usuario_comun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_usuario_comunMouseClicked(evt);
            }
        });
        jMenuBar1.add(m_usuario_comun);

        m_usuario_candidato.setText("Usuario Candidato");
        m_usuario_candidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_usuario_candidatoMouseClicked(evt);
            }
        });
        jMenuBar1.add(m_usuario_candidato);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usuario_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuario_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuario_c2ActionPerformed

    private void ag_usuario_candidatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ag_usuario_candidatoMouseClicked
        // TODO add your handling code here:
        try {
            String usuario,contraseña,nombre,correo,sexo;
            Date fecha;
            usuario=tf_usuario_c2.getText();
            contraseña=tf_contraseña_c2.getText();
            nombre=tf_nombre_c2.getText();
            correo=tf_correo_c2.getText();
            if(rb_masculino_c2.isSelected()){
                sexo="MASCULINO";
            }else{
                sexo="FEMENINO";

            }
            fecha=(Date) js_fecha_c2.getValue();
            //String name, String nombre_usuario, String contraseña,
            //Date fecha_nacimiento, String correo, String sexo, String nombre
            this.usuario.add(new Usuario_Candidato(nombre, usuario, contraseña, fecha, correo, sexo, nombre));

            
             
        Usuario_Candidato p1 =new Usuario_Candidato(nombre, usuario, contraseña, fecha, correo, sexo, nombre);
        
        admin_u_candidato ap=new admin_u_candidato("./Usuario_Candidato.cbm");
        ap.cargarArchivo();
        ap.setU_candidato(p1);
        ap.escribirArchivo();
        
        
            JOptionPane.showMessageDialog(jd_UsuarioCandidato, "usuario candidato registrado exitosamente");
            mi_login.setEnabled(true);
           
           

            tf_usuario_c2.setText("");
            tf_contraseña_c2.setText("");
            tf_nombre_c2.setText("");
            tf_correo_c2.setText("");
            rb_masculino_c2.setSelected(true);
            rb_femenino_c2.setSelected(false);
            

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(jd_UsuarioCandidato, "ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_ag_usuario_candidatoMouseClicked

    private void ag_usuario_comunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ag_usuario_comunMouseClicked
        // TODO add your handling code here:
        
        try {
            JFileChooser jfc=new JFileChooser();
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("Archivos de Texto", "txt");
        jfc.addChoosableFileFilter(filtro);
        
        int seleccion=jfc.showSaveDialog(this);
        
        FileWriter fw=null;
        BufferedWriter bw=null;
        File fichero=null;
        if(seleccion==JFileChooser.APPROVE_OPTION){
            try {
               if(jfc.getFileFilter().getDescription().equals("Archivos de Texto")){
                   fichero=new File(jfc.getSelectedFile().getPath()+".txt");
                   
               }else{
                   fichero=jfc.getSelectedFile();
               }
               fw=new FileWriter(fichero);
               bw=new BufferedWriter(fw);
               bw.write(ta_archivo_c1.getText());
               
               bw.flush();
           
               JOptionPane.showMessageDialog(jd_UsuarioComun, "Archivo guardado exitosamente");
               
            } catch (Exception e) {
                 e.printStackTrace();
            }
        }
        
        
        //.............
        String direccion=tf_direccion_c1.getText();
        String nombre=tf_nombre_c1.getText();
        
        String usuario_c1=tf_usuario_c1.getText();
        String contraseña_c1=tf_contraseña_c1.getText();
        
        Date fecha=(Date) js_fecha_c1.getValue();
        String correo1=tf_correo_c1.getText();
        String sexo;
        if(rb_femenino_c1.isSelected()){
            sexo="femenino";
        }else{
           sexo="masculino";
        }
        usuario.add(new Usuario_comun(direccion, fichero, nombre,
                usuario_c1, contraseña_c1, fecha, correo1, sexo, nombre));
        
        
        
        Usuario_comun p2 =new Usuario_comun(direccion, fichero, nombre,
                usuario_c1, contraseña_c1, fecha, correo1, sexo, nombre);
//        
        admin_u_comun ap=new admin_u_comun("./Usuario_Comun.cbm");
        ap.cargarArchivo();
        ap.setU_comun(p2);
        ap.escribirArchivo();
        
        
        
        //guardar 
        JOptionPane.showMessageDialog(jd_UsuarioComun, "Usuario comun registrado exitosamente");
        mi_login.setEnabled(true);
        tf_usuario_c1.setText("");
            tf_contraseña_c1.setText("");
            tf_nombre_c1.setText("");
            tf_correo_c1.setText("");
            tf_direccion_c1.setText("");
            rb_masculino_c1.setSelected(true);
            rb_femenino_c1.setSelected(false);
            ta_archivo_c1.setText("");
        
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(jd_UsuarioComun, "ocurrio un error y no se guardaron los datos");
        }
        
    
        
        
    }//GEN-LAST:event_ag_usuario_comunMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         jd_UsuarioComun.setModal(true);
        jd_UsuarioComun.pack();
        jd_UsuarioComun.setLocationRelativeTo(this);
        jd_UsuarioComun.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
          jd_UsuarioCandidato.setModal(true);
        jd_UsuarioCandidato.pack();
        jd_UsuarioCandidato.setLocationRelativeTo(this);
        jd_UsuarioCandidato.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void m_usuario_comunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_usuario_comunMouseClicked
        // TODO add your handling code here:
         menu_Usuario_Comun.setModal(true);
        menu_Usuario_Comun.pack();
        menu_Usuario_Comun.setLocationRelativeTo(this);
        menu_Usuario_Comun.setVisible(true);
    }//GEN-LAST:event_m_usuario_comunMouseClicked

    private void mi_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_loginActionPerformed
        // TODO add your handling code here:
          login.setModal(true);
        login.pack();
        login.setLocationRelativeTo(this);
        login.setVisible(true);
    }//GEN-LAST:event_mi_loginActionPerformed

    private void iniciar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciar_sesionMouseClicked
        for (int i = 0; i < usuario.size(); i++) {
            if(usuario.get(i).getNombre_usuario().equals(tf_usuario.getText())&&
                    usuario.get(i).getContraseña().equals(tf_contraseña.getText())){
                if(usuario.get(i)instanceof Usuario_comun){
                    usuario_comun_actual=(Usuario_comun)usuario.get(i);
                    m_usuario_comun.setEnabled(true);
                    mi_logout.setEnabled(true);
                    login.setVisible(false);
                    tf_usuario.setText("");
                    tf_contraseña.setText("");
         
             
                    
                }
                if(usuario.get(i)instanceof Usuario_Candidato){

                    mi_login.setEnabled(false);

                    
                          tf_nombre_c3.setText(usuario.get(i).getNombre());
                    tf_usuario_c3.setText(usuario.get(i).getNombre_usuario());
                    tf_correo_c3.setText(usuario.get(i).getCorreo());
                    tf_contraseña_c3.setText(usuario.get(i).getContraseña());

                    
                    
                    
                    usuario_candidato_actual=(Usuario_Candidato)usuario.get(i);
                    m_usuario_candidato.setEnabled(true);
                    mi_logout.setEnabled(true);
                     mi_login.setEnabled(false);
                    
                    tf_usuario.setText("");
                    tf_contraseña.setText("");
                    login.setVisible(false);
                    
                    
                }
                
            }
            
        }
        
        
    }//GEN-LAST:event_iniciar_sesionMouseClicked

    private void mi_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_logoutActionPerformed
        // TODO add your handling code here:
        m_usuario_candidato.setEnabled(false);
        m_usuario_comun.setEnabled(false);
        mi_login.setEnabled(true);
        mi_logout.setEnabled(false);
        
        
        tf_nombre1.setText("");
        tf_usuario1.setText("");
        tf_contraseña1.setText("");
       tf_correo1.setText("");
       tf_direccion1.setText("");
       tf_sexo1.setText("");
       ta_archivo_1.setText("");
        
        
    }//GEN-LAST:event_mi_logoutActionPerformed

    private void bt_verdatos_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_verdatos_perfilMouseClicked
        // TODO add your handling code here:
       tf_nombre1.setText(usuario_comun_actual.getNombre());
       tf_usuario1.setText(usuario_comun_actual.getNombre_usuario());
       tf_contraseña1.setText(usuario_comun_actual.getContraseña());
       tf_correo1.setText(usuario_comun_actual.getCorreo());
       tf_direccion1.setText(usuario_comun_actual.getDireccion());
       tf_sexo1.setText(usuario_comun_actual.getSexo());
       
       js_fecha1.setValue(usuario_comun_actual.getFecha_nacimiento());
       
       
        File fichero=null;
        FileReader fr=null;
        BufferedReader br=null;
        try {
          
                fichero=usuario_comun_actual.getArchivo();
                fr=new FileReader(fichero);
                
                br=new BufferedReader(fr);
                String linea;
                ta_archivo_1.setText("");
                while((linea=br.readLine())!= null){
                 
                    ta_archivo_1.append(linea);
                    ta_archivo_1.append("\n");
                }
            }
         catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
        }
        tf_nombre1.setEditable(false);
        tf_usuario1.setEditable(false);
        tf_contraseña1.setEditable(false);
       tf_correo1.setEditable(false);
       tf_direccion1.setEditable(false);
       tf_sexo1.setEditable(false);
       js_fecha1.setEnabled(false);
       ta_archivo_1.setEditable(false);
       
       bt_guardar_cambios_perfil.setEnabled(true);
       bt_modificar.setEnabled(true);
    }//GEN-LAST:event_bt_verdatos_perfilMouseClicked

    private void bt_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarMouseClicked
        // TODO add your handling code here:
        //modificar datos de perfil
        JOptionPane.showMessageDialog(menu_Usuario_Comun, "Escriba sonbre los campos que desea modificar");
         tf_nombre1.setEditable(true);
        tf_usuario1.setEditable(true);
        tf_contraseña1.setEditable(true);
       tf_correo1.setEditable(true);
       tf_direccion1.setEditable(true);
       tf_sexo1.setEditable(true);
       js_fecha1.setEnabled(true);
       ta_archivo_1.setEditable(true);
       
     
       
       

        
    }//GEN-LAST:event_bt_modificarMouseClicked

    private void bt_guardar_cambios_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardar_cambios_perfilMouseClicked
        // TODO add your handling code here:
        usuario_comun_actual.setName2(tf_nombre1.getText());
        usuario_comun_actual.setNombre(tf_nombre1.getText());
        usuario_comun_actual.setNombre_usuario(tf_usuario1.getText());
        usuario_comun_actual.setContraseña(tf_contraseña1.getText());
        usuario_comun_actual.setCorreo(tf_correo1.getText());
        usuario_comun_actual.setDireccion(tf_direccion1.getText());
        usuario_comun_actual.setSexo(tf_sexo1.getText());
        usuario_comun_actual.setFecha_nacimiento((Date) js_fecha1.getValue());
        
        
        
        try {
           
        FileWriter fw=null;
        BufferedWriter bw=null;
        File fichero=usuario_comun_actual.getArchivo();
       
               fw=new FileWriter(fichero,false);
               bw=new BufferedWriter(fw);
               bw.write(ta_archivo_1.getText());
               
               bw.flush();
            } catch (Exception e) {
                 e.printStackTrace();
            }
          tf_nombre1.setEditable(false);
        tf_usuario1.setEditable(false);
        tf_contraseña1.setEditable(false);
       tf_correo1.setEditable(false);
       tf_direccion1.setEditable(false);
       tf_sexo1.setEditable(false);
       js_fecha1.setEnabled(false);
       ta_archivo_1.setEditable(false);
        
    }//GEN-LAST:event_bt_guardar_cambios_perfilMouseClicked

    private void tabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabStateChanged
        // TODO add your handling code here:
        if(tab.getSelectedIndex()==2){
            admin_u_candidato ap=new admin_u_candidato("./Usuario_Candidato.cbm");
            
            ap.cargarArchivo();
            DefaultComboBoxModel modelo=new DefaultComboBoxModel(
                    ap.getLista_candidatos().toArray());//toArray convierte de array a arreglo
            cb_candidatos.setModel(modelo);
          
            
        }
        if(tab.getSelectedIndex()==1){
            admin_u_comun ap2=new admin_u_comun("./Usuario_Comun.cbm");
            ap2.cargarArchivo();
            DefaultComboBoxModel modelo2=new DefaultComboBoxModel(ap2.getLista_comun().toArray());
            cb_amigos.setModel(modelo2);
        }
//        
//         if (tab.getSelectedIndex() == 4) {
//             admin_u_comun ap3=new admin_u_comun("./Usuario_Comun.cbm");
//            ap3.cargarArchivo();
//             DefaultComboBoxModel modelo3=new DefaultComboBoxModel(ap3.getLista_comun().toArray());
//             
//            cb_amigos_mensaje.setModel(modelo3);
//        }
        
    }//GEN-LAST:event_tabStateChanged

    private void cb_candidatosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_candidatosItemStateChanged
        // TODO add your handling code here:
        
        DefaultListModel modelo_lista_seguidores=(DefaultListModel)jl_candidatos2.getModel();
        DefaultComboBoxModel modelo_c=(DefaultComboBoxModel)cb_candidatos_publicaciones.getModel();
         if(evt.getStateChange()==1){
            Usuario_Candidato temp=(Usuario_Candidato)cb_candidatos.getSelectedItem();
            if(temp !=null){
                admin_u_comun ap=new admin_u_comun("./Usuario_Comun.cbm");
//            
            ap.cargarArchivo();
                for (int i = 0; i < ap.getLista_comun().size(); i++) {
                    if(ap.getLista_comun().get(i).equals(usuario_comun_actual)){
                        ap.getLista_comun().get(i).setCandidatos_seguir(temp);
                        
                    }
                }
                ap.escribirArchivo();
                
                
                
                usuario_comun_actual.setCandidatos_seguir(temp);
                modelo_lista_seguidores.addElement(temp);
                modelo_c.addElement(temp);
                
                jl_candidatos2.setModel(modelo_lista_seguidores);
                cb_candidatos_publicaciones.setModel(modelo_c);
                
                
                
                
                
                
            }
         }
                
            
    }//GEN-LAST:event_cb_candidatosItemStateChanged

    private void dejar_seguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dejar_seguirMouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo_lista_seguidores=(DefaultListModel)jl_candidatos2.getModel();
        int x=jl_candidatos2.getSelectedIndex();
        if(x>=0){
            modelo_lista_seguidores.remove(x); 
            usuario_comun_actual.getCandidatos_seguir().remove(x);
        }
    }//GEN-LAST:event_dejar_seguirMouseClicked

    private void cb_amigosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_amigosItemStateChanged
        // TODO add your handling code here:
        admin_u_comun ap2=new admin_u_comun("./Usuario_Comun.cbm");
            ap2.cargarArchivo();
        DefaultListModel modelo_lista_amigos=(DefaultListModel)jl_amigos.getModel();
        DefaultComboBoxModel modelo_c=(DefaultComboBoxModel)cb_amigos_mensaje.getModel();
         if(evt.getStateChange()==1){
            Usuario_comun temp=(Usuario_comun)cb_amigos.getSelectedItem();
            if(temp !=null){
                
                for (int i = 0; i < ap2.getLista_comun().size(); i++) {
                    if(ap2.getLista_comun().get(i).equals(usuario_comun_actual)){
                        ap2.getLista_comun().get(i).setAmigos(temp);
                    }
                }
                ap2.escribirArchivo();
                
                usuario_comun_actual.setAmigos(temp);
                modelo_c.addElement(temp);
                modelo_lista_amigos.addElement(temp);
                jl_amigos.setModel(modelo_lista_amigos);
                cb_amigos_mensaje.setModel(modelo_c);
            }
         }
        
    }//GEN-LAST:event_cb_amigosItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //eliminar de mis amigos
        DefaultListModel modelo_amigos=(DefaultListModel)jl_amigos.getModel();
        int x=jl_amigos.getSelectedIndex();
        if(x>=0){
            modelo_amigos.remove(x); 
            usuario_comun_actual.getAmigos().remove(x);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
      String cadena="";
        for (int i = 0; i < usuario_comun_actual.getMensajes_recibidos().size(); i++) {
            cadena+=usuario_comun_actual.getMensajes_recibidos().get(i)+"\n ";
        }
        ta_mensajes.setText(cadena);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
     mensaje.setModal(true);
        mensaje.pack();
        mensaje.setLocationRelativeTo(this);
        mensaje.setVisible(true);
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void tf_usuario_c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuario_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuario_c3ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
      
//        p =new Publicaciones(area_publicacion.getText(),usuario_candidato_actual.getName());
//       
//        usuario_candidato_actual.setPublicaciones(p);
 publicacion.add(new Publicaciones(area_publicacion.getText(),usuario_candidato_actual.getName()));
          JOptionPane.showMessageDialog(menu_usuarioCandidato, "Publicacion Realizada");
          
       area_publicacion.setText("");
       
//     
        
//        publicacion.add(new Publicaciones(area_publicacion.getText()));
//      JOptionPane.showMessageDialog(menu_usuarioCandidato, "Publicacion Realizada");
    }//GEN-LAST:event_jButton5MouseClicked

    private void m_usuario_candidatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_usuario_candidatoMouseClicked

        // TODO add your handling code here:
          menu_usuarioCandidato.setModal(true);

        menu_usuarioCandidato.pack();
        menu_usuarioCandidato.setLocationRelativeTo(this);
        menu_usuarioCandidato.setVisible(true);
    }//GEN-LAST:event_m_usuario_candidatoMouseClicked



    private void enviar_mensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_mensajeMouseClicked
        // TODO add your handling code here:
        try {

            String asunto = tf_asunto.getText();
            String descripcion = ta_mensaje.getText();
            Date fecha = new Date();
            Usuario_comun receptor = (Usuario_comun) cb_amigos_mensaje.getSelectedItem();
            Usuario_comun emisor=(Usuario_comun)usuario_comun_actual;
                    correo = new mensajes(emisor, receptor, asunto, descripcion, fecha);
                    mensajes.add(correo);
                    emisor.setMensajes_enviados(mensajes);
                    receptor.setMensajes_recibidos(mensajes);

                
            
//            au = new adminUsuario("./usuario.cbm");
//            au.EscribirArchivo();
            JOptionPane.showMessageDialog(mensaje, "Mando el correo exitosamente");
            tf_asunto.setText("");
            ta_mensaje.setText("");
            System.out.println(emisor.getMensajes_enviados());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_enviar_mensajeMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
                                             
      String cadena="";
        for (int i = 0; i < usuario_comun_actual.getMensajes_enviados().size(); i++) {
            cadena+=usuario_comun_actual.getMensajes_enviados().get(i)+"\n ";
        }
        ta_mensajes1.setText(cadena);
    }//GEN-LAST:event_jButton6MouseClicked

    private void cb_candidatos_publicacionesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_candidatos_publicacionesItemStateChanged
        // TODO add your handling code here:
        
          if(evt.getStateChange()==1){
              String publi="";
            Usuario_Candidato temp=(Usuario_Candidato)cb_candidatos.getSelectedItem();
            if(temp !=null){
                for (int i = 0; i < publicacion.size(); i++) {
                   if(publicacion.get(i).getNombre_candidato().equals(temp.getName())){
                       publi+=publicacion.get(i)+"\n";
                   }
                   
                  
                }
                ta_publicaciones.setText(publi);
                
            }
                            
          }
        
    }//GEN-LAST:event_cb_candidatos_publicacionesItemStateChanged

    private void cargra_actaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cargra_actaMouseClicked
        // TODO add your handling code here:
        Scanner sc=null;
      
        File fichero=null;
        FileReader fr=null;
        BufferedReader br=null;
        ta_acta.setText("");
        try {
            JFileChooser jfc=new JFileChooser("./actas");
            //JFileChooser jfc=new JFileChooser("./");//Desde el directorio del proyecto
            FileNameExtensionFilter filtro= new FileNameExtensionFilter("Archivos de texto","txt");

            jfc.setFileFilter(filtro);

            //----------------------
            int seleccion=jfc.showOpenDialog(this);//Abrir archivo
           if(seleccion==JFileChooser.APPROVE_OPTION){
                fichero=jfc.getSelectedFile();
                ruta=jfc.getSelectedFile();
                fr=new FileReader(fichero);
                
                br=new BufferedReader(fr);
                
                ta_acta.setText("");
                while((linea=br.readLine())!= null){
                 
                    ta_acta.append(linea+"\n");
                    ta_acta.append("\n");
                }
           }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cargra_actaMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        if(ta_acta.getText()!=null){
            if(tf_votos.getText()!=null){
                
            
            actas ac=new actas(linea,Integer.parseInt(tf_votos.getText()),ruta);
            
            
            admin_actas ad=new admin_actas("./actas_votos.cbm");
            ad.cargarArchivo();
            ad.set_acta(ac);
            ad.escribirArchivo();
            JOptionPane.showMessageDialog(menu_Usuario_Comun, "se agregaron los votos al acta");
            ta_acta.setText("");
            tf_votos.setText("");
        }
        }
        
    }//GEN-LAST:event_jButton4MouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal_proyectolab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JPanel actas;
    private javax.swing.JButton ag_usuario_candidato;
    private javax.swing.JButton ag_usuario_comun;
    private javax.swing.JTextArea area_publicacion;
    private javax.swing.JButton bt_guardar_cambios_perfil;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_verdatos_perfil;
    private javax.swing.JPanel candidatos;
    private javax.swing.JButton cargra_acta;
    private javax.swing.JComboBox<String> cb_amigos;
    private javax.swing.JComboBox<String> cb_amigos_mensaje;
    private javax.swing.JComboBox<String> cb_candidatos;
    private javax.swing.JComboBox<String> cb_candidatos_publicaciones;
    private javax.swing.JButton dejar_seguir;
    private javax.swing.JButton enviar_mensaje;
    private javax.swing.JLabel imagen_principal;
    private javax.swing.JLabel imah;
    private javax.swing.JButton iniciar_sesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JDialog jd_UsuarioCandidato;
    private javax.swing.JDialog jd_UsuarioComun;
    private javax.swing.JList<String> jl_amigos;
    private javax.swing.JList<String> jl_candidatos2;
    private javax.swing.JSpinner js_fecha1;
    private javax.swing.JSpinner js_fecha_c1;
    private javax.swing.JSpinner js_fecha_c2;
    private javax.swing.JSpinner js_fecha_c3;
    private javax.swing.JDialog login;
    private javax.swing.JMenu m_usuario_candidato;
    private javax.swing.JMenu m_usuario_comun;
    private javax.swing.JDialog mensaje;
    private javax.swing.JDialog menu_Usuario_Comun;
    private javax.swing.JDialog menu_usuarioCandidato;
    private javax.swing.JPanel messenger;
    private javax.swing.JMenuItem mi_login;
    private javax.swing.JMenuItem mi_logout;
    private javax.swing.JPanel perfil;
    private javax.swing.JPanel publicaciones;
    private javax.swing.JRadioButton rb_femenino_c1;
    private javax.swing.JRadioButton rb_femenino_c2;
    private javax.swing.JRadioButton rb_femenino_c3;
    private javax.swing.JRadioButton rb_masculino_c1;
    private javax.swing.JRadioButton rb_masculino_c2;
    private javax.swing.JRadioButton rb_masculino_c3;
    private javax.swing.ButtonGroup sexo2;
    private javax.swing.JTextArea ta_acta;
    private javax.swing.JTextArea ta_archivo_1;
    private javax.swing.JTextArea ta_archivo_c1;
    private javax.swing.JTextField ta_mensaje;
    private javax.swing.JTextArea ta_mensajes;
    private javax.swing.JTextArea ta_mensajes1;
    private javax.swing.JTextArea ta_publicaciones;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextField tf_asunto;
    private javax.swing.JPasswordField tf_contraseña;
    private javax.swing.JTextField tf_contraseña1;
    private javax.swing.JPasswordField tf_contraseña_c1;
    private javax.swing.JPasswordField tf_contraseña_c2;
    private javax.swing.JPasswordField tf_contraseña_c3;
    private javax.swing.JTextField tf_correo1;
    private javax.swing.JTextField tf_correo_c1;
    private javax.swing.JTextField tf_correo_c2;
    private javax.swing.JTextField tf_correo_c3;
    private javax.swing.JTextField tf_direccion1;
    private javax.swing.JTextField tf_direccion_c1;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombre_c1;
    private javax.swing.JTextField tf_nombre_c2;
    private javax.swing.JTextField tf_nombre_c3;
    private javax.swing.JTextField tf_sexo1;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuario1;
    private javax.swing.JTextField tf_usuario_c1;
    private javax.swing.JTextField tf_usuario_c2;
    private javax.swing.JTextField tf_usuario_c3;
    private javax.swing.JTextField tf_votos;
    private javax.swing.JPanel usuarios;
    // End of variables declaration//GEN-END:variables
ArrayList<Usuario> usuario=new ArrayList();
Usuario_comun usuario_comun_actual;
Usuario_Candidato usuario_candidato_actual;
  ArrayList<mensajes> mensajes = new ArrayList();
 
 
 ArrayList<Publicaciones> publicacion = new ArrayList();
//  Publicaciones p ;
 
String usuario1="";
 mensajes correo = new mensajes();
  
   File ruta;
String linea;

String informacion_temporal_usuario="";
String informacion_temporal_nombre="";
String informacion_temporal_sexo="";
String informacion_temporal_contraseña="";
String informacion_temporal_correo="";



    
}
