/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolab_katherine_fabio;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author KATHERINE
 */
public class principal_proyectolab extends javax.swing.JFrame {

    /**
     * Creates new form principal_proyectolab
     */
    public principal_proyectolab() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo2 = new javax.swing.ButtonGroup();
        Sexo = new javax.swing.ButtonGroup();
        jd_UsuarioCandidato = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_usuario_c2 = new javax.swing.JTextField();
        ag_usuario_candidato = new javax.swing.JButton();
        rb_femenino_c2 = new javax.swing.JRadioButton();
        rb_masculino_c2 = new javax.swing.JRadioButton();
        tf_nombre_c2 = new javax.swing.JTextField();
        tf_correo_c2 = new javax.swing.JTextField();
        tf_contraseña_c2 = new javax.swing.JPasswordField();
        js_fecha_c2 = new javax.swing.JSpinner();
        jd_UsuarioComun = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_usuario_c1 = new javax.swing.JTextField();
        tf_nombre_c1 = new javax.swing.JTextField();
        tf_correo_c1 = new javax.swing.JTextField();
        tf_direccion_c1 = new javax.swing.JTextField();
        rb_femenino_c1 = new javax.swing.JRadioButton();
        rb_masculino_c1 = new javax.swing.JRadioButton();
        ag_usuario_comun = new javax.swing.JButton();
        tf_contraseña_c1 = new javax.swing.JPasswordField();
        js_fecha_c1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_archivo_c1 = new javax.swing.JTextArea();
        menu_Usuario_Comun = new javax.swing.JDialog();
        imagen_principal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("Usuario Candidato");

        jLabel11.setText("Usuario");

        jLabel12.setText("Contraseña");

        jLabel13.setText("Nombre Completo");

        jLabel14.setText("Correo");

        jLabel15.setText("Sexo");

        jLabel16.setText("Fecha de nacimiento");

        tf_usuario_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuario_c2ActionPerformed(evt);
            }
        });

        ag_usuario_candidato.setText("Agregar");
        ag_usuario_candidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ag_usuario_candidatoMouseClicked(evt);
            }
        });

        sexo2.add(rb_femenino_c2);
        rb_femenino_c2.setText("F");

        sexo2.add(rb_masculino_c2);
        rb_masculino_c2.setSelected(true);
        rb_masculino_c2.setText("M");

        js_fecha_c2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(915227160000L), null, new java.util.Date(946763160000L), java.util.Calendar.DAY_OF_YEAR));

        javax.swing.GroupLayout jd_UsuarioCandidatoLayout = new javax.swing.GroupLayout(jd_UsuarioCandidato.getContentPane());
        jd_UsuarioCandidato.getContentPane().setLayout(jd_UsuarioCandidatoLayout);
        jd_UsuarioCandidatoLayout.setHorizontalGroup(
            jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_nombre_c2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(tf_usuario_c2))
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addComponent(rb_femenino_c2)
                        .addGap(18, 18, 18)
                        .addComponent(rb_masculino_c2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_correo_c2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(tf_contraseña_c2))
                    .addComponent(js_fecha_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel10))
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(ag_usuario_candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jd_UsuarioCandidatoLayout.setVerticalGroup(
            jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_usuario_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tf_contraseña_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tf_nombre_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_correo_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(rb_femenino_c2)
                    .addComponent(rb_masculino_c2)
                    .addComponent(js_fecha_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(ag_usuario_candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Usuario Común ");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jLabel4.setText("fecha de nacimiento");

        jLabel5.setText("Correo");

        jLabel6.setText("sexo");

        jLabel7.setText("Nombre Completo");

        jLabel8.setText("Dirección");

        jLabel9.setText("Archivo de texto");

        Sexo.add(rb_femenino_c1);
        rb_femenino_c1.setText("F");

        Sexo.add(rb_masculino_c1);
        rb_masculino_c1.setSelected(true);
        rb_masculino_c1.setText("M");

        ag_usuario_comun.setText("Agregar");
        ag_usuario_comun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ag_usuario_comunMouseClicked(evt);
            }
        });

        js_fecha_c1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(915227160000L), null, new java.util.Date(946763160000L), java.util.Calendar.DAY_OF_YEAR));

        ta_archivo_c1.setColumns(20);
        ta_archivo_c1.setRows(5);
        jScrollPane1.setViewportView(ta_archivo_c1);

        javax.swing.GroupLayout jd_UsuarioComunLayout = new javax.swing.GroupLayout(jd_UsuarioComun.getContentPane());
        jd_UsuarioComun.getContentPane().setLayout(jd_UsuarioComunLayout);
        jd_UsuarioComunLayout.setHorizontalGroup(
            jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_direccion_c1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(tf_nombre_c1)
                                    .addComponent(tf_usuario_c1)))
                            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(107, 107, 107)
                                .addComponent(rb_femenino_c1)
                                .addGap(18, 18, 18)
                                .addComponent(rb_masculino_c1)))
                        .addGap(82, 82, 82)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_correo_c1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(tf_contraseña_c1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                                        .addComponent(js_fecha_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109))))))
                    .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(273, 273, 273)))
                .addContainerGap())
            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(ag_usuario_comun, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_UsuarioComunLayout.setVerticalGroup(
            jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(tf_usuario_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_contraseña_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(tf_nombre_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_correo_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(rb_femenino_c1)
                            .addComponent(rb_masculino_c1)
                            .addComponent(js_fecha_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(tf_direccion_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addComponent(ag_usuario_comun, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout menu_Usuario_ComunLayout = new javax.swing.GroupLayout(menu_Usuario_Comun.getContentPane());
        menu_Usuario_Comun.getContentPane().setLayout(menu_Usuario_ComunLayout);
        menu_Usuario_ComunLayout.setHorizontalGroup(
            menu_Usuario_ComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        menu_Usuario_ComunLayout.setVerticalGroup(
            menu_Usuario_ComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/descarga.jpg"))); // NOI18N
        getContentPane().add(imagen_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, -1));

        jMenu1.setText("Elecciones");

        jMenu4.setText("Registro");

        jMenuItem2.setText("Usuario Comun");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Usuario Candidato");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);

        jMenuItem4.setText("Login");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuario Común");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Usuario Candidato");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usuario_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuario_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuario_c2ActionPerformed

    private void ag_usuario_candidatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ag_usuario_candidatoMouseClicked
        // TODO add your handling code here:
        try {
            String usuario,contraseña,nombre,correo,sexo;
            Date fecha;
            usuario=tf_usuario_c2.getText();
            contraseña=tf_contraseña_c2.getText();
            nombre=tf_nombre_c2.getText();
            correo=tf_correo_c2.getText();
            if(rb_masculino_c2.isSelected()){
                sexo="MASCULINO";
            }else{
                sexo="FEMENINO";

            }
            fecha=(Date) js_fecha_c2.getValue();
            //String name, String nombre_usuario, String contraseña,
            //Date fecha_nacimiento, String correo, String sexo, String nombre
            this.usuario.add(new Usuario_Candidato(nombre, usuario, contraseña, fecha, correo, sexo, nombre));

            JOptionPane.showMessageDialog(jd_UsuarioCandidato, "usuario candidato registrado exitosamente");

           

            tf_usuario_c2.setText("");
            tf_contraseña_c2.setText("");
            tf_nombre_c2.setText("");
            tf_correo_c2.setText("");
            rb_masculino_c2.setSelected(true);
            rb_femenino_c2.setSelected(false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(jd_UsuarioCandidato, "ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_ag_usuario_candidatoMouseClicked

    private void ag_usuario_comunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ag_usuario_comunMouseClicked
        // TODO add your handling code here:
        
        try {
            JFileChooser jfc=new JFileChooser();
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("Archivos de Texto", "txt");
        jfc.addChoosableFileFilter(filtro);
        
        int seleccion=jfc.showSaveDialog(this);
        
        FileWriter fw=null;
        BufferedWriter bw=null;
        File fichero=null;
        if(seleccion==JFileChooser.APPROVE_OPTION){
            try {
               if(jfc.getFileFilter().getDescription().equals("Archivos de Texto")){
                   fichero=new File(jfc.getSelectedFile().getPath()+".txt");
                   
               }else{
                   fichero=jfc.getSelectedFile();
               }
               fw=new FileWriter(fichero);
               bw=new BufferedWriter(fw);
               bw.write(ta_archivo_c1.getText());
               
               bw.flush();
           
               JOptionPane.showMessageDialog(jd_UsuarioComun, "Archivo guardado exitosamente");
               
            } catch (Exception e) {
                 e.printStackTrace();
            }
        }
        
        
        //.............
        String direccion=tf_direccion_c1.getText();
        String nombre=tf_nombre_c1.getText();
        
        String usuario_c1=tf_usuario_c1.getText();
        String contraseña_c1=tf_contraseña_c1.getText();
        
        Date fecha=(Date) js_fecha_c1.getValue();
        String correo=tf_correo_c1.getText();
        String sexo;
        if(rb_femenino_c1.isSelected()){
            sexo="femenino";
        }else{
           sexo="masculino";
        }
        usuario.add(new Usuario_comun(direccion, fichero, nombre,
                usuario_c1, contraseña_c1, fecha, correo, sexo, nombre));
        
        
        
        JOptionPane.showMessageDialog(jd_UsuarioComun, "Usuario comun registrado exitosamente");
        tf_usuario_c1.setText("");
            tf_contraseña_c1.setText("");
            tf_nombre_c1.setText("");
            tf_correo_c1.setText("");
            tf_direccion_c1.setText("");
            rb_masculino_c1.setSelected(true);
            rb_femenino_c1.setSelected(false);
            ta_archivo_c1.setText("");
        
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(jd_UsuarioComun, "ocurrio un error y no se guardaron los datos");
        }
        
    
        
        
    }//GEN-LAST:event_ag_usuario_comunMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         jd_UsuarioComun.setModal(true);
        jd_UsuarioComun.pack();
        jd_UsuarioComun.setLocationRelativeTo(this);
        jd_UsuarioComun.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
          jd_UsuarioCandidato.setModal(true);
        jd_UsuarioCandidato.pack();
        jd_UsuarioCandidato.setLocationRelativeTo(this);
        jd_UsuarioCandidato.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
         menu_Usuario_Comun.setModal(true);
        menu_Usuario_Comun.pack();
        menu_Usuario_Comun.setLocationRelativeTo(this);
        menu_Usuario_Comun.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal_proyectolab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JButton ag_usuario_candidato;
    private javax.swing.JButton ag_usuario_comun;
    private javax.swing.JLabel imagen_principal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_UsuarioCandidato;
    private javax.swing.JDialog jd_UsuarioComun;
    private javax.swing.JSpinner js_fecha_c1;
    private javax.swing.JSpinner js_fecha_c2;
    private javax.swing.JDialog menu_Usuario_Comun;
    private javax.swing.JRadioButton rb_femenino_c1;
    private javax.swing.JRadioButton rb_femenino_c2;
    private javax.swing.JRadioButton rb_masculino_c1;
    private javax.swing.JRadioButton rb_masculino_c2;
    private javax.swing.ButtonGroup sexo2;
    private javax.swing.JTextArea ta_archivo_c1;
    private javax.swing.JPasswordField tf_contraseña_c1;
    private javax.swing.JPasswordField tf_contraseña_c2;
    private javax.swing.JTextField tf_correo_c1;
    private javax.swing.JTextField tf_correo_c2;
    private javax.swing.JTextField tf_direccion_c1;
    private javax.swing.JTextField tf_nombre_c1;
    private javax.swing.JTextField tf_nombre_c2;
    private javax.swing.JTextField tf_usuario_c1;
    private javax.swing.JTextField tf_usuario_c2;
    // End of variables declaration//GEN-END:variables
ArrayList<Usuario> usuario=new ArrayList();


    
}
