/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectolab_katherine_fabio;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author KATHERINE
 */
public class principal_proyectolab extends javax.swing.JFrame {

    /**
     * Creates new form principal_proyectolab
     */
    public principal_proyectolab() {
        initComponents();
        m_usuario_candidato.setEnabled(false);
        m_usuario_comun.setEnabled(false);
        mi_logout.setEnabled(false);
        mi_login.setEnabled(false);
        bt_guardar_cambios_perfil.setEnabled(false);
        bt_modificar.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo2 = new javax.swing.ButtonGroup();
        Sexo = new javax.swing.ButtonGroup();
        jd_UsuarioCandidato = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_usuario_c2 = new javax.swing.JTextField();
        ag_usuario_candidato = new javax.swing.JButton();
        rb_femenino_c2 = new javax.swing.JRadioButton();
        rb_masculino_c2 = new javax.swing.JRadioButton();
        tf_nombre_c2 = new javax.swing.JTextField();
        tf_correo_c2 = new javax.swing.JTextField();
        tf_contraseña_c2 = new javax.swing.JPasswordField();
        js_fecha_c2 = new javax.swing.JSpinner();
        jd_UsuarioComun = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_usuario_c1 = new javax.swing.JTextField();
        tf_nombre_c1 = new javax.swing.JTextField();
        tf_correo_c1 = new javax.swing.JTextField();
        tf_direccion_c1 = new javax.swing.JTextField();
        rb_femenino_c1 = new javax.swing.JRadioButton();
        rb_masculino_c1 = new javax.swing.JRadioButton();
        ag_usuario_comun = new javax.swing.JButton();
        tf_contraseña_c1 = new javax.swing.JPasswordField();
        js_fecha_c1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_archivo_c1 = new javax.swing.JTextArea();
        menu_Usuario_Comun = new javax.swing.JDialog();
        tab = new javax.swing.JTabbedPane();
        perfil = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_usuario1 = new javax.swing.JTextField();
        tf_nombre1 = new javax.swing.JTextField();
        tf_sexo1 = new javax.swing.JTextField();
        tf_correo1 = new javax.swing.JTextField();
        tf_direccion1 = new javax.swing.JTextField();
        tf_contraseña1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_archivo_1 = new javax.swing.JTextArea();
        bt_modificar = new javax.swing.JButton();
        bt_verdatos_perfil = new javax.swing.JButton();
        js_fecha1 = new javax.swing.JSpinner();
        bt_guardar_cambios_perfil = new javax.swing.JButton();
        usuarios = new javax.swing.JPanel();
        cb_amigos = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_amigos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        candidatos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_candidatos2 = new javax.swing.JList<>();
        dejar_seguir = new javax.swing.JButton();
        cb_candidatos = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        publicaciones = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_publicaciones = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        messenger = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_mensajes = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        ta_mensajes1 = new javax.swing.JTextArea();
        actas = new javax.swing.JPanel();
        login = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        iniciar_sesion = new javax.swing.JButton();
        tf_contraseña = new javax.swing.JPasswordField();
        tf_usuario = new javax.swing.JTextField();
        menu_usuarioCandidato = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        area_publicacion = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        tf_nombre_c3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        tf_usuario_c3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        rb_femenino_c3 = new javax.swing.JRadioButton();
        rb_masculino_c3 = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        tf_contraseña_c3 = new javax.swing.JPasswordField();
        jLabel32 = new javax.swing.JLabel();
        tf_correo_c3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        js_fecha_c3 = new javax.swing.JSpinner();
        jPanel9 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        mensaje = new javax.swing.JDialog();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        cb_amigos_mensaje = new javax.swing.JComboBox<>();
        tf_asunto = new javax.swing.JTextField();
        ta_mensaje = new javax.swing.JTextField();
        enviar_mensaje = new javax.swing.JButton();
        imagen_principal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mi_login = new javax.swing.JMenuItem();
        mi_logout = new javax.swing.JMenuItem();
        m_usuario_comun = new javax.swing.JMenu();
        m_usuario_candidato = new javax.swing.JMenu();

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setText("Usuario Candidato");

        jLabel11.setText("Usuario");

        jLabel12.setText("Contraseña");

        jLabel13.setText("Nombre Completo");

        jLabel14.setText("Correo");

        jLabel15.setText("Sexo");

        jLabel16.setText("Fecha de nacimiento");

        tf_usuario_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuario_c2ActionPerformed(evt);
            }
        });

        ag_usuario_candidato.setText("Agregar");
        ag_usuario_candidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ag_usuario_candidatoMouseClicked(evt);
            }
        });

        sexo2.add(rb_femenino_c2);
        rb_femenino_c2.setText("F");

        sexo2.add(rb_masculino_c2);
        rb_masculino_c2.setSelected(true);
        rb_masculino_c2.setText("M");

        js_fecha_c2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(915227160000L), null, new java.util.Date(946763160000L), java.util.Calendar.DAY_OF_YEAR));

        javax.swing.GroupLayout jd_UsuarioCandidatoLayout = new javax.swing.GroupLayout(jd_UsuarioCandidato.getContentPane());
        jd_UsuarioCandidato.getContentPane().setLayout(jd_UsuarioCandidatoLayout);
        jd_UsuarioCandidatoLayout.setHorizontalGroup(
            jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_nombre_c2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                        .addComponent(tf_usuario_c2))
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addComponent(rb_femenino_c2)
                        .addGap(18, 18, 18)
                        .addComponent(rb_masculino_c2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_correo_c2, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addComponent(tf_contraseña_c2))
                    .addComponent(js_fecha_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
            .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel10))
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(ag_usuario_candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jd_UsuarioCandidatoLayout.setVerticalGroup(
            jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_usuario_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tf_contraseña_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tf_nombre_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_UsuarioCandidatoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(tf_correo_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46)
                .addGroup(jd_UsuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(rb_femenino_c2)
                    .addComponent(rb_masculino_c2)
                    .addComponent(js_fecha_c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(ag_usuario_candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Usuario Común ");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        jLabel4.setText("fecha de nacimiento");

        jLabel5.setText("Correo");

        jLabel6.setText("sexo");

        jLabel7.setText("Nombre Completo");

        jLabel8.setText("Dirección");

        jLabel9.setText("Archivo de texto");

        Sexo.add(rb_femenino_c1);
        rb_femenino_c1.setText("F");

        Sexo.add(rb_masculino_c1);
        rb_masculino_c1.setSelected(true);
        rb_masculino_c1.setText("M");

        ag_usuario_comun.setText("Agregar");
        ag_usuario_comun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ag_usuario_comunMouseClicked(evt);
            }
        });

        js_fecha_c1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(915227160000L), null, new java.util.Date(946763160000L), java.util.Calendar.DAY_OF_YEAR));

        ta_archivo_c1.setColumns(20);
        ta_archivo_c1.setRows(5);
        jScrollPane1.setViewportView(ta_archivo_c1);

        javax.swing.GroupLayout jd_UsuarioComunLayout = new javax.swing.GroupLayout(jd_UsuarioComun.getContentPane());
        jd_UsuarioComun.getContentPane().setLayout(jd_UsuarioComunLayout);
        jd_UsuarioComunLayout.setHorizontalGroup(
            jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_direccion_c1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(tf_nombre_c1)
                                    .addComponent(tf_usuario_c1)))
                            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(107, 107, 107)
                                .addComponent(rb_femenino_c1)
                                .addGap(18, 18, 18)
                                .addComponent(rb_masculino_c1)))
                        .addGap(82, 82, 82)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_correo_c1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(tf_contraseña_c1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                                        .addComponent(js_fecha_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109))))))
                    .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(273, 273, 273)))
                .addContainerGap())
            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(ag_usuario_comun, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_UsuarioComunLayout.setVerticalGroup(
            jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UsuarioComunLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(tf_usuario_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_contraseña_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(tf_nombre_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_correo_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(rb_femenino_c1)
                            .addComponent(rb_masculino_c1)
                            .addComponent(js_fecha_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jd_UsuarioComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(tf_direccion_c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_UsuarioComunLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addComponent(ag_usuario_comun, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        tab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabStateChanged(evt);
            }
        });

        jLabel19.setText("Nombre");

        jLabel20.setText("Usuario");

        jLabel21.setText("Contraseña ");

        jLabel22.setText("Correo");

        jLabel23.setText("Sexo");

        jLabel24.setText("fecha de nacimiento");

        jLabel25.setText("direccion");

        jLabel26.setText("Archivo de Texto");

        ta_archivo_1.setColumns(20);
        ta_archivo_1.setRows(5);
        jScrollPane2.setViewportView(ta_archivo_1);

        bt_modificar.setText("Modificar");
        bt_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_modificarMouseClicked(evt);
            }
        });

        bt_verdatos_perfil.setText("VER DATOS PERFIL");
        bt_verdatos_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_verdatos_perfilMouseClicked(evt);
            }
        });

        js_fecha1.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(-55879890540000L), null, new java.util.Date(-55879890540000L), java.util.Calendar.DAY_OF_MONTH));

        bt_guardar_cambios_perfil.setText("Guardar cambios");
        bt_guardar_cambios_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardar_cambios_perfilMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout perfilLayout = new javax.swing.GroupLayout(perfil);
        perfil.setLayout(perfilLayout);
        perfilLayout.setHorizontalGroup(
            perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perfilLayout.createSequentialGroup()
                .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(perfilLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(perfilLayout.createSequentialGroup()
                                .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(tf_usuario1)
                                    .addComponent(tf_contraseña1)
                                    .addComponent(tf_correo1)))
                            .addComponent(bt_verdatos_perfil))
                        .addGap(28, 28, 28)
                        .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)))
                    .addGroup(perfilLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(bt_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_guardar_cambios_perfil)))
                .addGap(26, 26, 26)
                .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(js_fecha1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_sexo1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tf_direccion1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        perfilLayout.setVerticalGroup(
            perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(perfilLayout.createSequentialGroup()
                .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(perfilLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(bt_verdatos_perfil)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(perfilLayout.createSequentialGroup()
                        .addContainerGap(137, Short.MAX_VALUE)
                        .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(tf_sexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(tf_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(perfilLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel20)
                                    .addComponent(tf_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, perfilLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(js_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)))))
                .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(tf_direccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(perfilLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel26)
                        .addContainerGap(287, Short.MAX_VALUE))
                    .addGroup(perfilLayout.createSequentialGroup()
                        .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(perfilLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(tf_correo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66))
                            .addGroup(perfilLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                            .addComponent(bt_guardar_cambios_perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(78, 78, 78))))
        );

        tab.addTab("Perfil", perfil);

        cb_amigos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cb_amigos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_amigosItemStateChanged(evt);
            }
        });

        jLabel28.setText("Usuarios, agregar a mis amigos:");

        jl_amigos.setModel(new DefaultListModel()
        );
        jScrollPane4.setViewportView(jl_amigos);

        jButton1.setText("Eliminar de mis amigos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout usuariosLayout = new javax.swing.GroupLayout(usuarios);
        usuarios.setLayout(usuariosLayout);
        usuariosLayout.setHorizontalGroup(
            usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_amigos, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(244, 244, 244))
        );
        usuariosLayout.setVerticalGroup(
            usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(usuariosLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(cb_amigos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jButton1)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        tab.addTab("Ver usuarios", usuarios);

        jl_candidatos2.setModel(new DefaultListModel()
        );
        jScrollPane3.setViewportView(jl_candidatos2);

        dejar_seguir.setText("Dejar de seguir");
        dejar_seguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dejar_seguirMouseClicked(evt);
            }
        });

        cb_candidatos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_candidatosItemStateChanged(evt);
            }
        });

        jLabel27.setText("Elegir candidato para seguir");

        javax.swing.GroupLayout candidatosLayout = new javax.swing.GroupLayout(candidatos);
        candidatos.setLayout(candidatosLayout);
        candidatosLayout.setHorizontalGroup(
            candidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(candidatosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(candidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addGroup(candidatosLayout.createSequentialGroup()
                        .addComponent(cb_candidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, candidatosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dejar_seguir)
                .addGap(228, 228, 228))
        );
        candidatosLayout.setVerticalGroup(
            candidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(candidatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGroup(candidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(candidatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cb_candidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(candidatosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(dejar_seguir)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        tab.addTab("Ver Candidatos", candidatos);

        ta_publicaciones.setColumns(20);
        ta_publicaciones.setRows(5);
        jScrollPane6.setViewportView(ta_publicaciones);

        jButton4.setText("Actualizar Publicaciones");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout publicacionesLayout = new javax.swing.GroupLayout(publicaciones);
        publicaciones.setLayout(publicacionesLayout);
        publicacionesLayout.setHorizontalGroup(
            publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicacionesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        publicacionesLayout.setVerticalGroup(
            publicacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, publicacionesLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );

        tab.addTab("Publicaciones", publicaciones);

        jButton2.setText("Actualizar Buzon de entrada");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        ta_mensajes.setColumns(20);
        ta_mensajes.setRows(5);
        jScrollPane5.setViewportView(ta_mensajes);

        jButton3.setText("Nuevo mensaje");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton6.setText("Actualizar Buzon de salida");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        ta_mensajes1.setColumns(20);
        ta_mensajes1.setRows(5);
        jScrollPane8.setViewportView(ta_mensajes1);

        javax.swing.GroupLayout messengerLayout = new javax.swing.GroupLayout(messenger);
        messenger.setLayout(messengerLayout);
        messengerLayout.setHorizontalGroup(
            messengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messengerLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(messengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(messengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messengerLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messengerLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(messengerLayout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        messengerLayout.setVerticalGroup(
            messengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messengerLayout.createSequentialGroup()
                .addGroup(messengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, messengerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(messengerLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tab.addTab("Messenger", messenger);

        javax.swing.GroupLayout actasLayout = new javax.swing.GroupLayout(actas);
        actas.setLayout(actasLayout);
        actasLayout.setHorizontalGroup(
            actasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 853, Short.MAX_VALUE)
        );
        actasLayout.setVerticalGroup(
            actasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );

        tab.addTab("Actas", actas);

        javax.swing.GroupLayout menu_Usuario_ComunLayout = new javax.swing.GroupLayout(menu_Usuario_Comun.getContentPane());
        menu_Usuario_Comun.getContentPane().setLayout(menu_Usuario_ComunLayout);
        menu_Usuario_ComunLayout.setHorizontalGroup(
            menu_Usuario_ComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_Usuario_ComunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );
        menu_Usuario_ComunLayout.setVerticalGroup(
            menu_Usuario_ComunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_Usuario_ComunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );

        jLabel17.setText("Usuario");

        jLabel18.setText("Contraseña");

        iniciar_sesion.setText("Iniciar Sesión");
        iniciar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciar_sesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login.getContentPane());
        login.getContentPane().setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(54, 54, 54)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iniciar_sesion)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(tf_usuario))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(iniciar_sesion)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel37.setText("Nueva Publicacion");
        jPanel7.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        area_publicacion.setColumns(20);
        area_publicacion.setRows(5);
        jScrollPane7.setViewportView(area_publicacion);

        jPanel7.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 400, -1));

        jButton5.setText("Publicar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel7.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jTabbedPane2.addTab("Realizar Publicacion", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setText("Nombre Completo");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        jPanel8.add(tf_nombre_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 162, -1));

        jLabel29.setText("Usuario");
        jPanel8.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        tf_usuario_c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usuario_c3ActionPerformed(evt);
            }
        });
        jPanel8.add(tf_usuario_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 162, -1));

        jLabel30.setText("Sexo");
        jPanel8.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        rb_femenino_c3.setText("F");
        jPanel8.add(rb_femenino_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        rb_masculino_c3.setSelected(true);
        rb_masculino_c3.setText("M");
        jPanel8.add(rb_masculino_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel31.setText("Contraseña");
        jPanel8.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));
        jPanel8.add(tf_contraseña_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 166, -1));

        jLabel32.setText("Correo");
        jPanel8.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));
        jPanel8.add(tf_correo_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 166, -1));

        jLabel33.setText("Fecha de nacimiento");
        jPanel8.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        js_fecha_c3.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(915227160000L), null, new java.util.Date(946763160000L), java.util.Calendar.DAY_OF_YEAR));
        jPanel8.add(js_fecha_c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jTabbedPane2.addTab("Ver mi perfil", jPanel8);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel34.setText("Mis Votos");

        jProgressBar1.setMaximum(180000);
        jProgressBar1.setStringPainted(true);

        jLabel35.setText("0");

        jLabel36.setText("180,000");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel34))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 512, Short.MAX_VALUE)
                                .addComponent(jLabel36)))))
                .addGap(76, 76, 76))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel34)
                .addGap(43, 43, 43)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ver estadistica de votos", jPanel9);

        javax.swing.GroupLayout menu_usuarioCandidatoLayout = new javax.swing.GroupLayout(menu_usuarioCandidato.getContentPane());
        menu_usuarioCandidato.getContentPane().setLayout(menu_usuarioCandidatoLayout);
        menu_usuarioCandidatoLayout.setHorizontalGroup(
            menu_usuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        menu_usuarioCandidatoLayout.setVerticalGroup(
            menu_usuarioCandidatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_usuarioCandidatoLayout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jLabel39.setText("Para");

        jLabel40.setText("Asunto");

        jLabel41.setText("mensaje");

        cb_amigos_mensaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        enviar_mensaje.setText("enviar");
        enviar_mensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviar_mensajeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mensajeLayout = new javax.swing.GroupLayout(mensaje.getContentPane());
        mensaje.getContentPane().setLayout(mensajeLayout);
        mensajeLayout.setHorizontalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensajeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41))
                .addGap(27, 27, 27)
                .addGroup(mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_amigos_mensaje, 0, 367, Short.MAX_VALUE)
                    .addComponent(tf_asunto)
                    .addComponent(ta_mensaje))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mensajeLayout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(enviar_mensaje)
                .addGap(268, 268, 268))
        );
        mensajeLayout.setVerticalGroup(
            mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mensajeLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(cb_amigos_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(tf_asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(mensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(ta_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(enviar_mensaje)
                .addGap(39, 39, 39))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectolab_katherine_fabio/descarga.jpg"))); // NOI18N
        getContentPane().add(imagen_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, -1));

        jMenu1.setText("Elecciones");

        jMenu4.setText("Registro");

        jMenuItem2.setText("Usuario Comun");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Usuario Candidato");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);

        mi_login.setText("Login");
        mi_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_loginActionPerformed(evt);
            }
        });
        jMenu1.add(mi_login);

        mi_logout.setText("logout");
        mi_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_logoutActionPerformed(evt);
            }
        });
        jMenu1.add(mi_logout);

        jMenuBar1.add(jMenu1);

        m_usuario_comun.setText("Usuario Común");
        m_usuario_comun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_usuario_comunMouseClicked(evt);
            }
        });
        jMenuBar1.add(m_usuario_comun);

        m_usuario_candidato.setText("Usuario Candidato");
        m_usuario_candidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m_usuario_candidatoMouseClicked(evt);
            }
        });
        jMenuBar1.add(m_usuario_candidato);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usuario_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuario_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuario_c2ActionPerformed

    private void ag_usuario_candidatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ag_usuario_candidatoMouseClicked
        // TODO add your handling code here:
        try {
            String usuario,contraseña,nombre,correo,sexo;
            Date fecha;
            usuario=tf_usuario_c2.getText();
            contraseña=tf_contraseña_c2.getText();
            nombre=tf_nombre_c2.getText();
            correo=tf_correo_c2.getText();
            if(rb_masculino_c2.isSelected()){
                sexo="MASCULINO";
            }else{
                sexo="FEMENINO";

            }
            fecha=(Date) js_fecha_c2.getValue();
            //String name, String nombre_usuario, String contraseña,
            //Date fecha_nacimiento, String correo, String sexo, String nombre
            this.usuario.add(new Usuario_Candidato(nombre, usuario, contraseña, fecha, correo, sexo, nombre));

            
             
        Usuario_Candidato p =new Usuario_Candidato(nombre, usuario, contraseña, fecha, correo, sexo, nombre);
        
        admin_u_candidato ap=new admin_u_candidato("./Usuario_Candidato.cbm");
        ap.cargarArchivo();
        ap.setU_candidato(p);
        ap.escribirArchivo();
        
        
            JOptionPane.showMessageDialog(jd_UsuarioCandidato, "usuario candidato registrado exitosamente");
            mi_login.setEnabled(true);
           
           

            tf_usuario_c2.setText("");
            tf_contraseña_c2.setText("");
            tf_nombre_c2.setText("");
            tf_correo_c2.setText("");
            rb_masculino_c2.setSelected(true);
            rb_femenino_c2.setSelected(false);
            

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(jd_UsuarioCandidato, "ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_ag_usuario_candidatoMouseClicked

    private void ag_usuario_comunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ag_usuario_comunMouseClicked
        // TODO add your handling code here:
        
        try {
            JFileChooser jfc=new JFileChooser();
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("Archivos de Texto", "txt");
        jfc.addChoosableFileFilter(filtro);
        
        int seleccion=jfc.showSaveDialog(this);
        
        FileWriter fw=null;
        BufferedWriter bw=null;
        File fichero=null;
        if(seleccion==JFileChooser.APPROVE_OPTION){
            try {
               if(jfc.getFileFilter().getDescription().equals("Archivos de Texto")){
                   fichero=new File(jfc.getSelectedFile().getPath()+".txt");
                   
               }else{
                   fichero=jfc.getSelectedFile();
               }
               fw=new FileWriter(fichero);
               bw=new BufferedWriter(fw);
               bw.write(ta_archivo_c1.getText());
               
               bw.flush();
           
               JOptionPane.showMessageDialog(jd_UsuarioComun, "Archivo guardado exitosamente");
               
            } catch (Exception e) {
                 e.printStackTrace();
            }
        }
        
        
        //.............
        String direccion=tf_direccion_c1.getText();
        String nombre=tf_nombre_c1.getText();
        
        String usuario_c1=tf_usuario_c1.getText();
        String contraseña_c1=tf_contraseña_c1.getText();
        
        Date fecha=(Date) js_fecha_c1.getValue();
        String correo=tf_correo_c1.getText();
        String sexo;
        if(rb_femenino_c1.isSelected()){
            sexo="femenino";
        }else{
           sexo="masculino";
        }
        usuario.add(new Usuario_comun(direccion, fichero, nombre,
                usuario_c1, contraseña_c1, fecha, correo, sexo, nombre));
        
        
        
        Usuario_comun p =new Usuario_comun(direccion, fichero, nombre,
                usuario_c1, contraseña_c1, fecha, correo, sexo, nombre);
//        
        admin_u_comun ap=new admin_u_comun("./Usuario_Comun.cbm");
        ap.cargarArchivo();
        ap.setU_comun(p);
        ap.escribirArchivo();
        
        
        
        //guardar 
        JOptionPane.showMessageDialog(jd_UsuarioComun, "Usuario comun registrado exitosamente");
        mi_login.setEnabled(true);
        tf_usuario_c1.setText("");
            tf_contraseña_c1.setText("");
            tf_nombre_c1.setText("");
            tf_correo_c1.setText("");
            tf_direccion_c1.setText("");
            rb_masculino_c1.setSelected(true);
            rb_femenino_c1.setSelected(false);
            ta_archivo_c1.setText("");
        
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(jd_UsuarioComun, "ocurrio un error y no se guardaron los datos");
        }
        
    
        
        
    }//GEN-LAST:event_ag_usuario_comunMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         jd_UsuarioComun.setModal(true);
        jd_UsuarioComun.pack();
        jd_UsuarioComun.setLocationRelativeTo(this);
        jd_UsuarioComun.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
          jd_UsuarioCandidato.setModal(true);
        jd_UsuarioCandidato.pack();
        jd_UsuarioCandidato.setLocationRelativeTo(this);
        jd_UsuarioCandidato.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void m_usuario_comunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_usuario_comunMouseClicked
        // TODO add your handling code here:
         menu_Usuario_Comun.setModal(true);
        menu_Usuario_Comun.pack();
        menu_Usuario_Comun.setLocationRelativeTo(this);
        menu_Usuario_Comun.setVisible(true);
    }//GEN-LAST:event_m_usuario_comunMouseClicked

    private void mi_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_loginActionPerformed
        // TODO add your handling code here:
          login.setModal(true);
        login.pack();
        login.setLocationRelativeTo(this);
        login.setVisible(true);
    }//GEN-LAST:event_mi_loginActionPerformed

    private void iniciar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciar_sesionMouseClicked
        for (int i = 0; i < usuario.size(); i++) {
            if(usuario.get(i).getNombre_usuario().equals(tf_usuario.getText())&&
                    usuario.get(i).getContraseña().equals(tf_contraseña.getText())){
                if(usuario.get(i)instanceof Usuario_comun){
                    usuario_comun_actual=(Usuario_comun)usuario.get(i);
                    m_usuario_comun.setEnabled(true);
                    mi_logout.setEnabled(true);
                    
                    tf_usuario.setText("");
                    tf_contraseña.setText("");
                    login.setVisible(false);
                    for (int j = 0; j < usuario_comun_actual.getCandidatos_seguir().size(); j++) {
                        System.out.println(usuario_comun_actual.getCandidatos_seguir().get(i).getPublicaciones());
                    }
                    
                }
                if(usuario.get(i)instanceof Usuario_Candidato){
                    usuario_candidato_actual=(Usuario_Candidato)usuario.get(i);
                    m_usuario_candidato.setEnabled(true);
                    mi_logout.setEnabled(true);
                    
                    tf_usuario.setText("");
                    tf_contraseña.setText("");
                    login.setVisible(false);
                    
                    
                }
                
            }
            
        }
        
        
    }//GEN-LAST:event_iniciar_sesionMouseClicked

    private void mi_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_logoutActionPerformed
        // TODO add your handling code here:
        m_usuario_candidato.setEnabled(false);
        m_usuario_comun.setEnabled(false);
        
        
        tf_nombre1.setText("");
        tf_usuario1.setText("");
        tf_contraseña1.setText("");
       tf_correo1.setText("");
       tf_direccion1.setText("");
       tf_sexo1.setText("");
       ta_archivo_1.setText("");
        
        
    }//GEN-LAST:event_mi_logoutActionPerformed

    private void bt_verdatos_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_verdatos_perfilMouseClicked
        // TODO add your handling code here:
       tf_nombre1.setText(usuario_comun_actual.getNombre());
       tf_usuario1.setText(usuario_comun_actual.getNombre_usuario());
       tf_contraseña1.setText(usuario_comun_actual.getContraseña());
       tf_correo1.setText(usuario_comun_actual.getCorreo());
       tf_direccion1.setText(usuario_comun_actual.getDireccion());
       tf_sexo1.setText(usuario_comun_actual.getSexo());
       
       js_fecha1.setValue(usuario_comun_actual.getFecha_nacimiento());
       
       
        File fichero=null;
        FileReader fr=null;
        BufferedReader br=null;
        try {
          
                fichero=usuario_comun_actual.getArchivo();
                fr=new FileReader(fichero);
                
                br=new BufferedReader(fr);
                String linea;
                ta_archivo_1.setText("");
                while((linea=br.readLine())!= null){
                 
                    ta_archivo_1.append(linea);
                    ta_archivo_1.append("\n");
                }
            }
         catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
        }
        tf_nombre1.setEditable(false);
        tf_usuario1.setEditable(false);
        tf_contraseña1.setEditable(false);
       tf_correo1.setEditable(false);
       tf_direccion1.setEditable(false);
       tf_sexo1.setEditable(false);
       js_fecha1.setEnabled(false);
       ta_archivo_1.setEditable(false);
       
       bt_guardar_cambios_perfil.setEnabled(true);
       bt_modificar.setEnabled(true);
    }//GEN-LAST:event_bt_verdatos_perfilMouseClicked

    private void bt_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_modificarMouseClicked
        // TODO add your handling code here:
        //modificar datos de perfil
        JOptionPane.showMessageDialog(menu_Usuario_Comun, "Escriba sonbre los campos que desea modificar");
         tf_nombre1.setEditable(true);
        tf_usuario1.setEditable(true);
        tf_contraseña1.setEditable(true);
       tf_correo1.setEditable(true);
       tf_direccion1.setEditable(true);
       tf_sexo1.setEditable(true);
       js_fecha1.setEnabled(true);
       ta_archivo_1.setEditable(true);
       
     
       
       

        
    }//GEN-LAST:event_bt_modificarMouseClicked

    private void bt_guardar_cambios_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardar_cambios_perfilMouseClicked
        // TODO add your handling code here:
        usuario_comun_actual.setName2(tf_nombre1.getText());
        usuario_comun_actual.setNombre(tf_nombre1.getText());
        usuario_comun_actual.setNombre_usuario(tf_usuario1.getText());
        usuario_comun_actual.setContraseña(tf_contraseña1.getText());
        usuario_comun_actual.setCorreo(tf_correo1.getText());
        usuario_comun_actual.setDireccion(tf_direccion1.getText());
        usuario_comun_actual.setSexo(tf_sexo1.getText());
        usuario_comun_actual.setFecha_nacimiento((Date) js_fecha1.getValue());
        
        
        
        try {
           
        FileWriter fw=null;
        BufferedWriter bw=null;
        File fichero=usuario_comun_actual.getArchivo();
       
               fw=new FileWriter(fichero,false);
               bw=new BufferedWriter(fw);
               bw.write(ta_archivo_1.getText());
               
               bw.flush();
            } catch (Exception e) {
                 e.printStackTrace();
            }
          tf_nombre1.setEditable(false);
        tf_usuario1.setEditable(false);
        tf_contraseña1.setEditable(false);
       tf_correo1.setEditable(false);
       tf_direccion1.setEditable(false);
       tf_sexo1.setEditable(false);
       js_fecha1.setEnabled(false);
       ta_archivo_1.setEditable(false);
        
    }//GEN-LAST:event_bt_guardar_cambios_perfilMouseClicked

    private void tabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabStateChanged
        // TODO add your handling code here:
        if(tab.getSelectedIndex()==2){
            admin_u_candidato ap=new admin_u_candidato("./Usuario_Candidato.cbm");
            
            ap.cargarArchivo();
            DefaultComboBoxModel modelo=new DefaultComboBoxModel(
                    ap.getLista_candidatos().toArray());//toArray convierte de array a arreglo
            cb_candidatos.setModel(modelo);
            
        }
        if(tab.getSelectedIndex()==1){
            admin_u_comun ap2=new admin_u_comun("./Usuario_Comun.cbm");
            ap2.cargarArchivo();
            DefaultComboBoxModel modelo2=new DefaultComboBoxModel(ap2.getLista_comun().toArray());
            cb_amigos.setModel(modelo2);
        }
        
         if (tab.getSelectedIndex() == 4) {
             admin_u_comun ap3=new admin_u_comun("./Usuario_Comun.cbm");
            ap3.cargarArchivo();
             DefaultComboBoxModel modelo3=new DefaultComboBoxModel(ap3.getLista_comun().toArray());
             
            cb_amigos_mensaje.setModel(modelo3);
        }
        
    }//GEN-LAST:event_tabStateChanged

    private void cb_candidatosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_candidatosItemStateChanged
        // TODO add your handling code here:
        
        DefaultListModel modelo_lista_seguidores=(DefaultListModel)jl_candidatos2.getModel();
         if(evt.getStateChange()==1){
            Usuario_Candidato temp=(Usuario_Candidato)cb_candidatos.getSelectedItem();
            if(temp !=null){
                admin_u_comun ap=new admin_u_comun("./Usuario_Comun.cbm");
//            
            ap.cargarArchivo();
                for (int i = 0; i < ap.getLista_comun().size(); i++) {
                    if(ap.getLista_comun().get(i).equals(usuario_comun_actual)){
                        ap.getLista_comun().get(i).setCandidatos_seguir(temp);
                        
                    }
                }
                ap.escribirArchivo();
                
                usuario_comun_actual.setCandidatos_seguir(temp);
                modelo_lista_seguidores.addElement(temp);
                jl_candidatos2.setModel(modelo_lista_seguidores);
            }
         }
                
            
    }//GEN-LAST:event_cb_candidatosItemStateChanged

    private void dejar_seguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dejar_seguirMouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo_lista_seguidores=(DefaultListModel)jl_candidatos2.getModel();
        int x=jl_candidatos2.getSelectedIndex();
        if(x>=0){
            modelo_lista_seguidores.remove(x); 
            usuario_comun_actual.getCandidatos_seguir().remove(x);
        }
    }//GEN-LAST:event_dejar_seguirMouseClicked

    private void cb_amigosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_amigosItemStateChanged
        // TODO add your handling code here:
        admin_u_comun ap2=new admin_u_comun("./Usuario_Comun.cbm");
            ap2.cargarArchivo();
        DefaultListModel modelo_lista_amigos=(DefaultListModel)jl_amigos.getModel();
         if(evt.getStateChange()==1){
            Usuario_comun temp=(Usuario_comun)cb_amigos.getSelectedItem();
            if(temp !=null){
                
                for (int i = 0; i < ap2.getLista_comun().size(); i++) {
                    if(ap2.getLista_comun().get(i).equals(usuario_comun_actual)){
                        ap2.getLista_comun().get(i).setAmigos(temp);
                    }
                }
                ap2.escribirArchivo();
                
                usuario_comun_actual.setAmigos(temp);
                modelo_lista_amigos.addElement(temp);
                jl_amigos.setModel(modelo_lista_amigos);
            }
         }
        
    }//GEN-LAST:event_cb_amigosItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        //eliminar de mis amigos
        DefaultListModel modelo_amigos=(DefaultListModel)jl_amigos.getModel();
        int x=jl_amigos.getSelectedIndex();
        if(x>=0){
            modelo_amigos.remove(x); 
            usuario_comun_actual.getAmigos().remove(x);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
      String cadena="";
        for (int i = 0; i < usuario_comun_actual.getMensajes_recibidos().size(); i++) {
            cadena+=usuario_comun_actual.getMensajes_recibidos().get(i)+"\n ";
        }
        ta_mensajes.setText(cadena);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
//        // TODO add your handling code here:
//        //nuevo mensaje
//        String emisor=usuario_comun_actual.getName2();
//        String contenido="";
//        int cont=1;
//        for (int i = 0; i < usuario_comun_actual.getAmigos().size(); i++) {
//            contenido+=cont+")"+usuario_comun_actual.getAmigos().get(i).getName2()+"\n";
//            cont++;
//        }
//       int op=Integer.parseInt( JOptionPane.showInputDialog("A que usuario le quiere enviar un mensaje?\n" + contenido));
//       String receptor=usuario_comun_actual.getAmigos().get(op-1).getName2();
//       
//        enviarMensaje(emisor,receptor);

     mensaje.setModal(true);
        mensaje.pack();
        mensaje.setLocationRelativeTo(this);
        mensaje.setVisible(true);
        
        

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        //publicaciones
        String cadena_publicaciones="";
//        admin_u_comun ap=new admin_u_comun("./Usuario_Comun.cbm");
//            
//            ap.cargarArchivo();
//            for (int i = 0; i < ap.getLista_comun().size(); i++) {
//            if(ap.getLista_comun().get(i).equals(usuario_comun_actual)){
//                publicaciones+=ap.getLista_comun().get(i).getCandidatos_seguir().get(i).getPublicaciones()+"\n";
//            }
//        }
        for (int i = 0; i < usuario_comun_actual.getCandidatos_seguir().size(); i++) {
            cadena_publicaciones+=usuario_comun_actual.getCandidatos_seguir().get(i).getPublicaciones()+"\n";
//            System.out.println(usuario_comun_actual.getCandidatos_seguir().get(i).getTexto_publicacion()+"\n hola\n");
        
        }
        ta_publicaciones.setText(cadena_publicaciones);
    }//GEN-LAST:event_jButton4MouseClicked

    private void tf_usuario_c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usuario_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usuario_c3ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
      
        p =new Publicaciones(area_publicacion.getText(),usuario_candidato_actual.getName());
       
        usuario_candidato_actual.setPublicaciones(p);
          JOptionPane.showMessageDialog(menu_usuarioCandidato, "Publicacion Realizada");
          System.out.println(p);
       area_publicacion.setText("");
       
//     
        
//        publicacion.add(new Publicaciones(area_publicacion.getText()));
//      JOptionPane.showMessageDialog(menu_usuarioCandidato, "Publicacion Realizada");
    }//GEN-LAST:event_jButton5MouseClicked

    private void m_usuario_candidatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m_usuario_candidatoMouseClicked
        // TODO add your handling code here:
          menu_usuarioCandidato.setModal(true);
        menu_usuarioCandidato.pack();
        menu_usuarioCandidato.setLocationRelativeTo(this);
        menu_usuarioCandidato.setVisible(true);
    }//GEN-LAST:event_m_usuario_candidatoMouseClicked

    private void enviar_mensajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_mensajeMouseClicked
        // TODO add your handling code here:
        try {

            String asunto = tf_asunto.getText();
            String descripcion = ta_mensaje.getText();
            Date fecha = new Date();
            Usuario_comun receptor = (Usuario_comun) cb_amigos_mensaje.getSelectedItem();
            Usuario_comun emisor=(Usuario_comun)usuario_comun_actual;
                    correo = new mensajes(emisor, receptor, asunto, descripcion, fecha);
                    mensajes.add(correo);
                    emisor.setMensajes_enviados(mensajes);
                    receptor.setMensajes_recibidos(mensajes);

                
            
//            au = new adminUsuario("./usuario.cbm");
//            au.EscribirArchivo();
            JOptionPane.showMessageDialog(this, "Mando el correo exitosamente");
            tf_asunto.setText("");
            ta_mensaje.setText("");
            System.out.println(emisor.getMensajes_enviados());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_enviar_mensajeMouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
                                             
      String cadena="";
        for (int i = 0; i < usuario_comun_actual.getMensajes_enviados().size(); i++) {
            cadena+=usuario_comun_actual.getMensajes_enviados().get(i)+"\n ";
        }
        ta_mensajes1.setText(cadena);
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal_proyectolab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal_proyectolab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Sexo;
    private javax.swing.JPanel actas;
    private javax.swing.JButton ag_usuario_candidato;
    private javax.swing.JButton ag_usuario_comun;
    private javax.swing.JTextArea area_publicacion;
    private javax.swing.JButton bt_guardar_cambios_perfil;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton bt_verdatos_perfil;
    private javax.swing.JPanel candidatos;
    private javax.swing.JComboBox<String> cb_amigos;
    private javax.swing.JComboBox<String> cb_amigos_mensaje;
    private javax.swing.JComboBox<String> cb_candidatos;
    private javax.swing.JButton dejar_seguir;
    private javax.swing.JButton enviar_mensaje;
    private javax.swing.JLabel imagen_principal;
    private javax.swing.JButton iniciar_sesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JDialog jd_UsuarioCandidato;
    private javax.swing.JDialog jd_UsuarioComun;
    private javax.swing.JList<String> jl_amigos;
    private javax.swing.JList<String> jl_candidatos2;
    private javax.swing.JSpinner js_fecha1;
    private javax.swing.JSpinner js_fecha_c1;
    private javax.swing.JSpinner js_fecha_c2;
    private javax.swing.JSpinner js_fecha_c3;
    private javax.swing.JDialog login;
    private javax.swing.JMenu m_usuario_candidato;
    private javax.swing.JMenu m_usuario_comun;
    private javax.swing.JDialog mensaje;
    private javax.swing.JDialog menu_Usuario_Comun;
    private javax.swing.JDialog menu_usuarioCandidato;
    private javax.swing.JPanel messenger;
    private javax.swing.JMenuItem mi_login;
    private javax.swing.JMenuItem mi_logout;
    private javax.swing.JPanel perfil;
    private javax.swing.JPanel publicaciones;
    private javax.swing.JRadioButton rb_femenino_c1;
    private javax.swing.JRadioButton rb_femenino_c2;
    private javax.swing.JRadioButton rb_femenino_c3;
    private javax.swing.JRadioButton rb_masculino_c1;
    private javax.swing.JRadioButton rb_masculino_c2;
    private javax.swing.JRadioButton rb_masculino_c3;
    private javax.swing.ButtonGroup sexo2;
    private javax.swing.JTextArea ta_archivo_1;
    private javax.swing.JTextArea ta_archivo_c1;
    private javax.swing.JTextField ta_mensaje;
    private javax.swing.JTextArea ta_mensajes;
    private javax.swing.JTextArea ta_mensajes1;
    private javax.swing.JTextArea ta_publicaciones;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextField tf_asunto;
    private javax.swing.JPasswordField tf_contraseña;
    private javax.swing.JTextField tf_contraseña1;
    private javax.swing.JPasswordField tf_contraseña_c1;
    private javax.swing.JPasswordField tf_contraseña_c2;
    private javax.swing.JPasswordField tf_contraseña_c3;
    private javax.swing.JTextField tf_correo1;
    private javax.swing.JTextField tf_correo_c1;
    private javax.swing.JTextField tf_correo_c2;
    private javax.swing.JTextField tf_correo_c3;
    private javax.swing.JTextField tf_direccion1;
    private javax.swing.JTextField tf_direccion_c1;
    private javax.swing.JTextField tf_nombre1;
    private javax.swing.JTextField tf_nombre_c1;
    private javax.swing.JTextField tf_nombre_c2;
    private javax.swing.JTextField tf_nombre_c3;
    private javax.swing.JTextField tf_sexo1;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuario1;
    private javax.swing.JTextField tf_usuario_c1;
    private javax.swing.JTextField tf_usuario_c2;
    private javax.swing.JTextField tf_usuario_c3;
    private javax.swing.JPanel usuarios;
    // End of variables declaration//GEN-END:variables
ArrayList<Usuario> usuario=new ArrayList();
Usuario_comun usuario_comun_actual;
Usuario_Candidato usuario_candidato_actual;
  ArrayList<mensajes> mensajes = new ArrayList();
 
 
 ArrayList<Publicaciones> publicacion = new ArrayList();
  Publicaciones p ;
 
String usuario1="";
 mensajes correo = new mensajes();
    

    
}
